[build]
pkgs = [
  "python311",
  "pip",
  "rustc",
  "cargo",
  "gcc",
  "libffi",
  "openssl",
  "pkg-config",
  "libgomp",
  "libomp"
]

[phases.setup]
commands = [
  "python -m pip install --upgrade pip"
]