[build]
aptPackages = ["libgomp1"]
pkgs = [
  "python311",
  "pip",
  "rustc",
  "cargo",
  "gcc",
  "gfortran",
  "blas",
  "lapack"
]

[phases.setup]
commands = [
  "python -m pip install --upgrade pip"
]